<div class="field Rut required">
    <label class="label" for="rut">
        <span><?= $block->escapeHtml(__('Rut Cliente')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="rut" id="rut" value="" title="<?= $block->escapeHtmlAttr(__('Rut Cliente')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
    
<div class="field Giro required">
    <label class="label" for="giro">
        <span><?= $block->escapeHtml(__('Giro Cliente')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="giro" id="giro" value="" title="<?= $block->escapeHtmlAttr(__('Giro Cliente')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

<div class="field ComunaDespacho required">
    <label class="label" for="comunaDespacho">
        <span><?= $block->escapeHtml(__('Comuna Despacho')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="comunaDespacho" id="comunaDespacho" value="" title="<?= $block->escapeHtmlAttr(__('Comuna Despacho')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

<div class="field ComunaFacturacion required">
    <label class="label" for="comunaFacturacion">
        <span><?= $block->escapeHtml(__('Comuna Facturacion')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="comunaFacturacion" id="comunaFacturacion" value="" title="<?= $block->escapeHtmlAttr(__('Comuna Facturacion')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

<div class="field razonSocial required">
    <label class="label" for="razonSocial">
        <span><?= $block->escapeHtml(__('Razon Social')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="razonSocial" id="razonSocial" value="" title="<?= $block->escapeHtmlAttr(__('Razon Social')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

<div class="field nombreFantasia required">
    <label class="label" for="nombreFantasia">
        <span><?= $block->escapeHtml(__('Nombre Fantasia')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="nombreFantasia" id="nombreFantasia" value="" title="<?= $block->escapeHtmlAttr(__('Nombre Fantasia')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>



<!-- FrontEnd Informacion usuario Nuevo/Existente -->